### ISSUE TITLE
Begin returns true no matter what.

### ISSUE THREAD

**Issue by jcfain** [DFRobot/DFRobot_DF2301Q#2]
https://github.com/DFRobot/DFRobot_DF2301Q/blob/784d2051a9603791f3cb2cb01b5d9ea35c50a42c/DFRobot_DF2301Q.cpp#L30

**Comment by qsjhyy** [comment]
Previously, I only made the formatting of I2C and UART consistent. Now, during the initialization of I2C, I tested the communication to ensure it is working properly. Thank you for your suggestion.
