### ISSUE TITLE
No serial output

### ISSUE THREAD

**Issue by dsssssssss9** [DFRobot/DFRobot_DF2301Q#4]
Running Linux 
Have tried both versions of Arduino IDE
Have tried several different UNO boards

Code compiles & uploads fine but no output from serial monitor

**Comment by qsjhyy** [comment]
Can you provide more information? In my test, the serial monitor does have output, even without a sensor. Perhaps you can take a look at our wiki page: https://wiki.dfrobot.com/SKU_SEN0539-EN_Gravity_Voice_Recognition_Module_I2C_UART.
![image](https://github.com/DFRobot/DFRobot_DF2301Q/assets/78136558/e1f57408-30bc-48ad-b3a6-7bfea09328b3)

**Comment by qsjhyy** [comment]
Because there has been no valid reply for too long, it is temporarily closed.
