### ISSUE TITLE
Additional output for end of wake word listening DF2301Q_UART_MSG_DATA_NOTIFY_WAKEUPEXIT

### ISSUE THREAD

**Issue by pinter75** [DFRobot/DFRobot_DF2301Q#6]
Is it possible to get a CMDID output or similar access when the wake word timeout has occurred?

I see DF2301Q_UART_MSG_DATA_NOTIFY_WAKEUPEXIT in the library, but how can I access it?

It would be great to get a message that the unit has stopped listening. I am using the UART mode.

Thanks!

**Comment by qsjhyy** [comment]
Yes, when the module is in UART mode, it does have that functionality. However, it wasn't needed before, so the library doesn't have a dedicated API for it. But the module does automatically prompt that information, and you can actively receive and identify it. Brief information is as follows:
![image](https://github.com/DFRobot/DFRobot_DF2301Q/assets/78136558/224d93fb-f301-410e-b3a2-4e545b2e6966)
![image](https://github.com/DFRobot/DFRobot_DF2301Q/assets/78136558/4a4986d3-aae7-4a3d-a81e-966d5c47a4df)
![image](https://github.com/DFRobot/DFRobot_DF2301Q/assets/78136558/350f6914-037d-4999-94b0-400dec806fd1)

**Comment by qsjhyy** [comment]
No follow-up for a long time, so temporarily closed.
