### ISSUE TITLE
How do I setup for ESP32-S3?

### ISSUE THREAD

**Issue by vonmartins** [DFRobot/DFRobot_DF2301Q#7]
Recently I bought an esp32-s3 and tried the code but the connection between the module and the esp32s3 doesn't work. Do I need to change anything? If so, what?

**Comment by qsjhyy** [comment]
你好，这个模块是没有对esp32s3进行兼容测试的，如果你需要使用，你可以尝试替换esp32s3能够成功的通信接口：
![image](https://github.com/DFRobot/DFRobot_DF2301Q/assets/78136558/29261bd4-04a1-466f-a284-f06a42f90130)

![image](https://github.com/DFRobot/DFRobot_DF2301Q/assets/78136558/e127648a-1449-44b1-87fd-22adda9791ef)

**Comment by vonmartins** [comment]
UART example worked perfectly with ESP32S3. I2C haven't tried it yet
