### ISSUE TITLE
I2C enter wake up state

### ISSUE THREAD

**Issue by biospank** [DFRobot/DFRobot_DF2301Q#8]
Hi there, 
I noticed that in UART mode it's possible to enter wake up state programmatically using [this](https://github.com/DFRobot/DFRobot_DF2301Q/blob/7b02d7f5822d1966ebfb693f8aec8eadd2cade4d/DFRobot_DF2301Q.h#L309C3-L309C55)
Is there any way to do the same using I2C?

Thank you

**Comment by qsjhyy** [comment]
Yes, as shown in the following screenshot of the i2c example：
![image](https://github.com/DFRobot/DFRobot_DF2301Q/assets/78136558/2f0dd9bd-4d75-4564-b80c-cfdb1f06f5d8)
